stages:
  - build
  - doc

image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install logpickr_sdk/

build_wheel:
  stage: build
  script:
    - cd logpickr_sdk
    - python setup.py bdist_wheel
    - cd dist
    - cp *.whl logpickr_sdk.whl
  artifacts:
    paths:
      - logpickr_sdk/dist/*.whl

pages:
  stage: doc
  dependencies:
    - build_wheel
  script:
    - pip install sphinx sphinx-rtd-theme
    # should already be installed by the package, but better safe than sorry
    - ls logpickr_sdk/dist/
    - mkdir sphinxdocs/_static
    - mv logpickr_sdk/dist/logpickr_sdk.whl sphinxdocs/_static/
    - cd sphinxdocs
    - ls _static/
    - make html
    - mv _build/html/_downloads/*/logpickr_sdk.whl _build/html/_downloads/
    - rm -r  _build/html/_downloads/*/
    - sed -i -E 's#_downloads/.+/logpickr_sdk.whl#_downloads/logpickr_sdk.whl#g' _build/html/howto.html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
