.install_sdk_template: &install_sdk
  before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install igrafx_mining_sdk/

.security_and_quality_rules_template: &security_and_quality_rules
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH =~ /^release.*/
    - if: $CI_COMMIT_TAG

stages:
  - test
  - build
  - doc

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  <<: *security_and_quality_rules
  after_script:
    - cat gl-code-quality-report.json | docker run -i stedolan/jq -c 'map({description,fingerprint,location,severity})|unique_by({fingerprint})' > tmp.json && mv tmp.json gl-code-quality-report.json

bandit-sast:
  <<: *security_and_quality_rules

semgrep-sast:
  <<: *security_and_quality_rules

gemnasium-python-dependency_scanning:
  <<: *security_and_quality_rules

image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

setup:
  stage: .pre
  script:
    # Wheel package file name convention is the following:
    # {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl
    # Thus it cannot contain any '-' character in it's version number
    # See https://peps.python.org/pep-0491/#file-name-convention

    # Get version number from init_file
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install toml
    - version=$(python -c "import toml; pyproject = toml.load('pyproject.toml'); print(pyproject['tool']['poetry']['version'])")
    - wheel_filename="igrafx_mining_sdk-${version}-py3-none-any.whl"
    - echo "VERSION=${version}" >> build.env
    - echo "WHEEL_FILENAME=${wheel_filename}" >> build.env
  artifacts:
    reports:
      dotenv: build.env

cache:
  paths:
    - .cache/pip
    - venv/

build_wheel:
  stage: build
  <<: *install_sdk
  script:
    - echo "VERSION=${VERSION}" >> build_wheel.env
    - echo "WHEEL_FILENAME=${WHEEL_FILENAME}" >> build_wheel.env
    - cd igrafx_mining_sdk
    - sed -i -E "s#version=.*,#version=\"${VERSION}\",#g" setup.py
    - python setup.py bdist_wheel
    - cd dist
    - cp *.whl igrafx_mining_sdk.whl
    - cp igrafx_mining_sdk.whl ${WHEEL_FILENAME}
  artifacts:
    paths:
      - igrafx_mining_sdk/dist/${WHEEL_FILENAME}
      - build_wheel.env

pages:
  stage: doc
  needs:
    job: build_wheel
    artifacts: true
  script:
    - source build_wheel.env
    - echo "${WHEEL_FILENAME}"
    - pip install sphinx sphinx-rtd-theme
    # should already be installed by the package, but better safe than sorry
    - ls igrafx_mining_sdk/dist/
    - mkdir sphinxdocs/_static
    - mv igrafx_mining_sdk/dist/${WHEEL_FILENAME} sphinxdocs/_static/
    - sed -i -E "s#igrafx_mining_sdk.whl#${WHEEL_FILENAME}#g" sphinxdocs/howto.rst
    - cd sphinxdocs
    - ls _static/
    - make html
    - mv _build/html/_downloads/*/${WHEEL_FILENAME} _build/html/_downloads/
    - rm -r  _build/html/_downloads/*/
    - sed -i -E "s#_downloads/.+/${WHEEL_FILENAME}#_downloads/${WHEEL_FILENAME}#g" _build/html/howto.html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - tags
