name: Update Conda Package

on:
  release:
    types: [published]

jobs:
  update-conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch new package version and source URL from PyPI
        id: get_version
        run: |
          VERSION=$(curl -s https://pypi.org/pypi/igrafx-mining-sdk/json | jq -r .info.version)
          URL=$(curl -s https://pypi.org/pypi/igrafx-mining-sdk/json | jq -r ".urls[0].url")
          SHA256=$(curl -sL $URL | sha256sum | awk '{print $1}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "URL=$URL" >> $GITHUB_ENV
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Fork and Clone Conda-Forge Feedstock
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo fork conda-forge/igrafx-mining-sdk-feedstock --clone=true --remote=true
          cd igrafx-mining-sdk-feedstock
          
          git remote add upstream https://github.com/conda-forge/igrafx-mining-sdk-feedstock.git
          git fetch upstream
          git checkout main
          git merge upstream/main

          cd recipe
          # Update version, URL, and SHA256 in meta.yaml
          sed -i "s/{% set version = \".*\" %}/{% set version = \"$VERSION\" %}/g" meta.yaml
          sed -i "s|url: .*|url: \"$URL\"|g" meta.yaml
          sed -i "s|sha256: .*|sha256: \"$SHA256\"|g" meta.yaml

      - name: Commit Changes and Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd igrafx-mining-sdk-feedstock
          git checkout -b update-$VERSION
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add recipe/meta.yaml
          git commit -m "Update Conda package to version $VERSION"
          git push origin update-$VERSION
          
          # Install GitHub CLI
          sudo apt update && sudo apt install -y gh

          # Create PR to Conda-Forge
          gh pr create --title "Update Conda package to $VERSION" --body "Automatically updating Conda package to $VERSION" --base main --head update-$VERSION --repo conda-forge/igrafx-mining-sdk-feedstock

  validate-and-merge:
      needs: update-conda
      runs-on: ubuntu-latest
      steps:
        - name: Wait for CI Checks to Pass
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            PR_NUMBER=${{ env.PR_NUMBER }}
            
            # Wait for all CI checks to pass
            STATUS="pending"
            while [[ "$STATUS" != "success" ]]; do
              STATUS=$(gh pr checks $PR_NUMBER --repo conda-forge/igrafx-mining-sdk-feedstock | jq -r '.status')
              if [[ "$STATUS" == "failure" ]]; then
                echo "❌ Tests failed! PR will not be merged."
                exit 1
              fi
              echo "🔄 Waiting for tests to complete..."
              sleep 30
            done

        - name: Approve PR
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh pr review ${{ env.PR_NUMBER }} --approve --repo conda-forge/igrafx-mining-sdk-feedstock

        - name: Merge PR
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh pr merge ${{ env.PR_NUMBER }} --merge --repo conda-forge/igrafx-mining-sdk-feedstock